baseURL = "https://example.com/"
title = "Eugen Standard"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"

  [languages.fr]
    languageName = "Francais"
    weight = 3
    contentDir = "content/fr"
	
	[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
