baseURL = "https://eugen-standard.pages.dev/"
title = "Eugen Standard"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"

  [languages.fr]
    languageName = "Francais"
    weight = 3
    contentDir = "content/fr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
imgBase = "https://pub-29b0e1892b2b48d697b4fa55e3cef646.r2.dev"